name: Hello-world
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: build step
         run: echo "A demo build"
     test:
      run-on: ubuntu-latest
      steps:
       - name: Test Phase
        run: echo "Running test cases"

     deploy:
       run-on: ubuntu-latest
       steps:
         -name: deploy the app
         run: echo "deploying the app"
