name: Deploy html to s3 
on: push
jobs:
  deploy:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code from repo
     uses: action/checkout@v4
   - name: configure aws credentials
      uses: aws action/configure-aws-credential
    with: 
    aws aws asses ky id
     aws aws asses ky id
    -name: code static code to s3
      run: |
      aws s3 syn
